include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_if_elements_to_conditional_expressions: false
    use_setters_to_change_properties: false
    prefer_function_declarations_over_variables: false
    no_logic_in_create_state: false