name: linum
description: Budgeting App by Invest it!

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.3+20

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  badges: ^3.1.2
  cloud_firestore: ^5.0.2
  code_builder: ^4.1.0
  collection: ^1.17.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  dart_style: ^2.2.3
  easy_localization: ^3.0.2
  easy_localization_loader: ^2.0.2
  enum_to_string: ^2.0.1

  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flat_buffers: ^23.5.26
  flip_card: ^0.7.0 # Don't update to 0.6.0

  flutter:
    sdk: flutter
  
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.0.8
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.7.0
  logger: ^2.3.0
  mockito: ^5.3.2
  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
  objectbox_generator: ^4.0.1
  package_info_plus: ^8.0.0
  path: ^1.8.2
  provider: ^6.0.2
  rxdart: ^0.28.0
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^6.1.1
  tuple: ^2.0.0
  url_launcher: ^6.1.2
  url_launcher_ios: ^6.0.15
  uuid: ^4.4.0

  

dev_dependencies:
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.14
  flutter_test: 
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.4.1
  lint: ^2.1.2
  localization_tools:
    git:
      url: "https://github.com/damattl/localization-tools.git"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/res/appicon.png"
  image_path_ios: "assets/res/appicon-ios.jpg"
  # adaptive_icon_background: "#86bd42"
  # adaptive_icon_foreground: "assets/res/appicon.png"

flutter_native_splash:
  color: "#FAFAFA"
  color_dark: "#303030"
  image: "assets/images/InvestIt-Logo-Standardfarbe-Web-250x250.png"
  image_dark: "assets/images/InvestIt-Logo-Standardfarbe-Web-250x250.png"
  android: true
  ios: true
  fullscreen: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

object_box:
  output_dir: "lib/generated/object_box"

