#   GitHub Automated Tests - GitHub Action that is triggered when someone tries to merge to development, which runs all tests and analyzes the code
#
#   Author: NightmindOfficial
#   Co-Author: n/a
#

name: CI Core Checks

# Triggered when PR request with development base is opened

on:
  pull_request:
    branches: [ development ]
  workflow_dispatch: # To manually run the workflow

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:

  code-analysis-and-testing:
    name: Code Analysis and Testing
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # - name: Set up Dart SDK
    #   uses: dart-lang/setup-dart@v1.3
    #   with:
    #     sdk: 'stable'

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install npm
      run: npm install
      
    - name: Run build file
      run: npm run build
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

    - name: Prepare Firebase Option Configuration
      run: |
        curl -sL https://firebase.tools | bash
        dart pub global activate flutterfire_cli
        ls
        flutterfire --version
        flutterfire configure -o lib/firebase/firebase_options.g.dart \
          -p linum-5d9f6 -y --platforms="android,ios" \
          -i de.investitacademy.linum \
          -a de.investitacademy.linum \
          -w de.investitacademy.linum \
          -m de.investitacademy.linum \
          --windows-app-id de.investitacademy.linum 

    - name: Delete previous Builds
      run: flutter clean

    - name: Get Flutter Pub
      run: flutter pub get
    
    - name: Set up Dart Pub
      run: dart pub get
    
    - name: Analyze Flutter Code
      run: flutter analyze
    
    - name: Flutter Test
      run: flutter test
