#   GitHub Automated Tests - GitHub Action that is triggered when someone tries to merge to development, which runs all tests and analyzes the code
#
#   Author: NightmindOfficial
#   Co-Author: n/a
#

name: Automatic Integration Tests

# Triggered when PR request with development base is opened

on:
  # push:
  #   branches: [ development ]
  workflow_dispatch: # To manually run the workflow

jobs:
  integration-tests-ios:
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    strategy:
      # A set of different configurations of the virtual  
      # environment.
      matrix:
        device:
        - "iPhone 11 Simulator (15.2)"
        #- "iPhone 13 Pro Simulator (15.2)"
        #- "iPhone 13 Pro Max Simulator (15.2)"
        #- "iPhone 8 Simulator (15.2)"
        #- "iPhone 8 Plus Simulator (15.2)"
        #- "iPhone SE (2nd generation) Simulator (15.2)"
      # When set to true, GitHub cancels all in-progress jobs if any        
      # matrix job fails.
      fail-fast: false
    runs-on: macOS-latest
    steps:
    - name: "List all simulators"
      run: "xcrun xctrace list devices"
    - name: "Start Simulator"
      run: |
        UDID=$(
          xcrun xctrace list devices |
          awk \
            -F ' ' \
            -v 'device=${{ matrix.device }}' \
            'NR > 4 {uid=$NF;$NF=""; NF--;} $0 == device {print substr(uid, 2,36)}'
        )
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    # The branch or tag ref that triggered the workflow will be 
    # checked out.
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'dev' or 'beta'
    - name: "Run Flutter Driver tests"
      run: "flutter drive --target=test_driver/app.dart"
